### ISSUE TITLE
Attempting to test the example

### ISSUE THREAD

**Issue by jmarreroc** [CMark/osgi-swagger-connector#1]
Hello Mark!

First of all, thank you for your great work! 
I'm just trying to use OSGi + JAX-RS Connector(with the appropriate connector you mentioned) + Swagger connector. And in the starting point of launching the example test you include (com.cmark.swagger.osgi.example) I can see that the SwaggerResourceTracker register two different services correctly: 
- HelloService : Correctly because its annotated with swagger expressions
- com.wordnik.swagger.jersey.listing.ApiListingResourceJSON : Wich I guess that is responsible of serving the '/api-docs' requests.

So, when i launch the jUnit test (or use the browser) typing : 'http://localhost:8280/services/hello/Mark' works correctly showing me 'Welcome Mark to Swagger OSGi Connector!'. However whe i type 'http://localhost:8280/services/api-docs' the server response me Error 500 with no trace...

I recognize that i'm little lost how to debug because the swagger core is written in scala and don't know where can i start to debug. Did I forget something in the test case?

Sorry for my rusty english and thank you for your time!

**Comment by cmark** [comment]
Hi @jmarreroc,

Thanks for trying out OSGi-JAX-RS + Swagger Connector.
I've tried the example project in a fresh installment, and it works perfectly for me.

Did you launched the example project by using the launch config in the project named `SwaggerOsgiConnector.launch`, or used a custom one?
You can check if more than one `Guava` bundle is registered in the launch config and make sure you have only version `15.0.0` selected.

The `com.cmark.swagger.publisher` project has a class called `SwaggerListingResource` which is a simple subclass of the mentioned `com.wordnik.swagger.jersey.listing.ApiListingResourceJSON`. I use this class to debug any problems with the resource listing (aka the api-docs endpoint). 
To use it: 
1. You have to change the `OSGI-INF/apiListingResource.xml` by changing the `class` and `provided services` fields to use the `com.cmark.swagger.publisher.SwaggerListingResource` class instead. 
2. Put breakpoints in both method. If you want to catch exceptions, you can register a JAX-RS `ExceptionHandler` or just define a try-catch block in the methods mentioned. 
3. Then relaunch the OSGi runtime and catch the exception.

I hope this helps, let me know your findings.

Best, 
Mark

**Comment by jmarreroc** [comment]
Hello Mark!

Thank your fast answer and for the info tfor debugging exceptions! I include your bundles as jars in my target platform, but now for debugging i prefer to use the sources. And finally I solve the problem! I just forgot to include in the launcher configuration the json4s (3.2.10) library. Maybe I removed it in some stupid moment ^^' 

Thank your for your support!

**Comment by cmark** [comment]
Cool! I'm glad you've successfully solved the issue. 

If you have any further question, feel free to ask, and let me know your suggestions on what and how to improve.

**Comment by jmarreroc** [comment]
Hello Mark, its me again ^^'

All works pretty fine and I can view the documentation shown in jSon format as i type petitions. I'm using an embebbed jetty server on OSGi context, and my next step is to use the ui module you define, but i'm not sure how to use it with jetty. I'm just including the ui bundle in my structure as a required plugin and in the launch configuration as the last one to start, but i think thats not enough... So, here is my question: How did you define the servlet container of the ui module in your tests? Do i need to include it in a servlet container as a .jar?

Thank you for your time Mark and have a nice weekend!

**Comment by cmark** [comment]
Hi @jmarreroc,

To run the `api-viewer`, you need to include the `com.cmark.swagger.ui` project in your launch configuration, or use the provided `SwaggerOsgiConnector` launch configuration. You don't have to define anything else, leave start levels on default. Then launch the configuration, and point your browser to `http://localhost:8280/services/api-viewer/index.html`. You should be able to see the Swagger API document.

Behind the scenes the ui bundle uses `Equinox HTTP registry` to register a servlet to handle incoming request on the `services/api-viewer` URL, so you don't have to do anything or include any jar.

I'll update the readme on Github to reflect usage of the UI bundle.
I hope this helps,
Mark

**Comment by jmarreroc** [comment]
Hi again Mark!

Finally it works! Thank you for all!

Kind regards

**Comment by cmark** [comment]
:+1:
